application: honus-1064
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


- url: /script.js
  static_dir: script.js
  
  
- url: /scripts 
  static_dir: scripts
  
  
- url: /stylesheet.css
  static_dir: stylesheet.css
  
  
- url: /stylesheets
  static_dir: stylesheets
  
  
- url: .*
  script: main.php